<?php

namespace AppBundle\Repository;

/**
 * EstablishmentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstablishmentsRepository extends \Doctrine\ORM\EntityRepository
{
}
